# setwd("Documents/Classes/STAT 434/project")

# Consider Google's hourly bucket data, as generated by hourly.py from WRDS
goog.data = read.table("goog_hourly.csv", header=T, sep=",")

# Convert date strings of form "20130102" into R Date objects
# WARNING: this overwrites the DATE column of the data frame
goog.data$DATE = strptime(as.character(goog.data$DATE), format="%Y%m%d %H:%M:%S")

# Let us find the variance from May 2013 onward
# First, we need to determine the initial index to start at
start_idx = 100
# which(goog.data$DATE == strptime("20130501 09:00:00", format="%Y%m%d %H:%M:%S"), arr.ind=T)

# Lagged volatility over 100 time deltas up to idx, inclusive.
# Assumes we start from the beginning of data.
volatility = function(data, idx) {
	EV = mean(data[(idx - start_idx + 1):idx])
	dist_sum_sqrd = 0
	for (i in (idx - start_idx + 1):idx) {
		dist_sum_sqrd = dist_sum_sqrd + (EV - data[i])^2
	}
	return (dist_sum_sqrd / start_idx)
}

goog.data$vol = seq(0, 1, length(goog.data$PRICE))

# Compute volatilities
for (i in start_idx:length(goog.data$PRICE)) {
	goog.data$vol[i] = volatility(goog.data$PRICE, i)
}

# Let's see those volatilies
plot(goog.data$DATE, goog.data$vol, type="l", main="Volatility of GOOG", xlab="Date", ylab="Variance (Dollars^2)")
par(new=T)
plot(goog.data$DATE, goog.data$PRICE, type="l", main="", xlab="", ylab="", col=4, axes="F")
# throw the volatility scale on the right hand side
axis(4, pretty(goog.data$PRICE))
mtext("Stock Return (Dollars)", side=4)